### ISSUE TITLE
Minebot incompatibility

### ISSUE THREAD

**Issue by beppe9000** [thebombzen/AutoSwitch#2]
Here is the relevant part of the stack trace:
```
java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.get(Unknown Source)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at thebombzen.mods.thebombzenapi.ThebombzenAPI.isExtendedKeyDown(ThebombzenAPI.java:427)
	at thebombzen.mods.autoswitch.AutoSwitch.clientTick(AutoSwitch.java:170)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_AutoSwitch_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1711)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1080)
```
Minebot replaces some keybinds with its own subclass in order to simulate mouse and key presses but your mod doesn't accout for the changed keycode.

I found another mod with the [same problem](https://github.com/michaelzangl/minebot/issues/108#issuecomment-221137272) and proposed a fix [here](https://github.com/Zyin055/zyinhud/issues/59#issuecomment-221224348) that may apply in this case too.

**Comment by thebombzen** [comment]
This is actually relevant to ThebombzenAPI. Refile the bug report there because that's where it'll get fixed.

**Comment by thebombzen** [comment]
Oops, it appears it is an AutoSwitch issue.

**Comment by thebombzen** [comment]
Fairly certain I just fixed this. Refile if I didn't.

**Comment by beppe9000** [comment]
Wow, that was fast!
Could you make a release? I'm on windows and there is no batch file so I don't know how to compile :(
